### ISSUE TITLE
AspNet Core support

### ISSUE THREAD

**Issue by senj** [alonam/NLoad#39]
When I try to build a standalone asp.net core application (with .exe), 
I can start the app but no threads get spawned.

When I run it in Visual Studio or via the ```dotnet run``` command it works.

Any ideas why this happens?

**Comment by senj** [comment]
Ok this was my bad, i forgot to include the setting files on build.

**Comment by alonam** [comment]
you're welcome to make changes.
when a PR is merged, appveyor automatically deploys the package to nuget.org
